---
- name: Install ruby
  hosts: all
  become: true
  tasks:
  - name: Install ruby and required packages
    apt: 
      name: ['ruby-full', 'ruby-bundler', 'build-essential'] 
      update_cache: yes
      state: present
